name: Check Commits

on: [workflow_call]

permissions: {}

jobs:
  build:
    permissions:
      contents: read
      pull-requests: read
    name: Check commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: huggingface/action-check-commits@7546dfa9ac8bd8270ea7ca5f137319aaa62e1599 # v1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          max-commits: "10"
          min-words: "3"
          forbidden-words: "fixup"
