name: Security Checks

on:
  push:

permissions:
  contents: read

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          REF_NAME: ${{ github.ref_name }}
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
          EVENT_NAME: ${{ github.event_name }}
          COMMITS_JSON: ${{ toJson(github.event.commits) }}
          PR_COMMITS: ${{ github.event.pull_request.commits }}
        run: |
          if [ "$EVENT_NAME" == "push" ]; then
            echo "depth=$(($(jq length <<< "$COMMITS_JSON") + 2))" >> $GITHUB_ENV
            echo "branch=$REF_NAME" >> $GITHUB_ENV
          fi
          if [ "$EVENT_NAME" == "pull_request" ]; then
            echo "depth=$(($PR_COMMITS+2))" >> $GITHUB_ENV
            echo "branch=$HEAD_REF" >> $GITHUB_ENV
          fi
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
        with:
          ref: ${{ env.branch }}
          fetch-depth: ${{ env.depth }}
      - name: Scan for secrets
        uses: trufflesecurity/trufflehog@27b0417c16317ca9a472a9a8092acce143b49c55  # main