name: Security Checks

on:
  push:

permissions:
  contents: read

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          REF_NAME: ${{ github.ref_name }}
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
          EVENT_NAME: ${{ github.event_name }}
          COMMITS_JSON: ${{ toJson(github.event.commits) }}
          PR_COMMITS: ${{ github.event.pull_request.commits }}
        run: |
          if [ "$EVENT_NAME" == "push" ]; then
            echo "depth=$(($(jq length <<< "$COMMITS_JSON") + 2))" >> $GITHUB_ENV
            echo "branch=$REF_NAME" >> $GITHUB_ENV
          fi
          if [ "$EVENT_NAME" == "pull_request" ]; then
            echo "depth=$(($PR_COMMITS+2))" >> $GITHUB_ENV
            echo "branch=$HEAD_REF" >> $GITHUB_ENV
          fi
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          ref: ${{env.branch}}
          fetch-depth: ${{env.depth}}
      - name: Scan for secrets
        uses: trufflesecurity/trufflehog@37b77001d0174ebec2fcca2bd83ff83a6d45a3ab  # main